version: '3.8'
services:
  msgateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: msgateway-service
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://localhost:7073/eureka
networks:
  ms-network:
    driver: bridge
